### ISSUE TITLE
spec2nii ge Pfile: spec2nii.GE.ge_read_pfile.UnknownPfile: No Pfile mapper for pulse sequence = slaser

### ISSUE THREAD

**Issue by weberam2** [wtclarke/fsl_mrs#19]
Hi Will,
I couldn't find this error elsewhere, so I hope this is the right place.
I am trying to analyze some GE semi LASER data, but I get an error right away trying to convert the Pfile to Nifti

`spec2nii ge P39424.7`

Gives me this error:

`Traceback (most recent call last):
  File "/home/weberam2/miniconda3/bin/spec2nii", line 8, in <module>
    sys.exit(main())
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/spec2nii.py", line 521, in main
    spec2nii(*args)
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/spec2nii.py", line 272, in __init__
    args.func(args)
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/spec2nii.py", line 473, in ge
    self.imageOut, self.fileoutNames = read_pfile(args.file, args.fileout)
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/GE/ge_pfile.py", line 66, in read_pfile
    pfile = Pfile(filename)
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/GE/ge_read_pfile.py", line 133, in __init__
    self.map_data()
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/GE/ge_read_pfile.py", line 275, in map_data
    mapper = self.get_mapper
  File "/home/weberam2/miniconda3/lib/python3.8/site-packages/spec2nii/GE/ge_read_pfile.py", line 209, in get_mapper
    raise UnknownPfile("No Pfile mapper for pulse sequence = %s" % psd)
spec2nii.GE.ge_read_pfile.UnknownPfile: No Pfile mapper for pulse sequence = slaser
`

I'm happy to send you the Pfile if that helps

Cheers,

Alex W.

**Comment by wtclarke** [comment]
Hi Alex,

I'm sorry I never replied to this for some reason. I'm making some progress through some old issues. If you still had that file I'd be happy to take a look and include it.

Will

**Comment by wtclarke** [comment]
Closing for now. Happy to reopen if needed.

**Comment by weberam2** [comment]
Hi William,

I tested this again and still have the issue with GE and Semi-Laser sequence (spec2nii version 0.4.9)

Here is an example P-file of a GE Semi-Laser sequence 
[P18432.zip](https://github.com/wtclarke/fsl_mrs/files/11391086/P18432.zip)

**Comment by wtclarke** [comment]
Thanks Alex. I've made a quick fix and will publish it in an upcoming version. Is this data that I can include with the public test set?

**Comment by weberam2** [comment]
Yes, feel free to use this Pfile
Please let me know when you have published the next version :)

Also, let me know if you need more GE Pfiles

**Comment by zhangrentu** [comment]
The GE CSI data also exist above issue. (UserWarning: The interpretation of pfile CSI data is poorly tested; rotations or transpositions of the CSI grid could be present. Spec2nii currently lacks a complete set of CSI test data. Please get in touch to help solve this issue! warn('The interpretation of pfile CSI data is poorly tested; rotations or transpositions of the')

**Comment by zhangrentu** [comment]
Hi Alex,  
the script of spec2nii.GE.ge_read_pfile did not read the NEX dimension of GE CSI data
